name: Android

on: [push, pull_request]

jobs:
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug
        run: bash ./gradlew build test jacocoTestReport jacocoTestCoverageVerification codeCoverageReport
      - name: Upload coverage to Codecov
        run: |
          curl -Os https://uploader.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov
